on:
  push:
    branches:
      - main
jobs:
  logstash_en_git:
    runs-on: ubuntu-latest
    steps:
    - name: descargarCodigo
      uses: actions/checkout@v4

    - name: instalarlogstash
      run: |
        wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo gpg --dearmor -o /usr/share/keyrings/elastic-keyring.gpg
        sudo apt-get install apt-transport-https
        echo "deb [signed-by=/usr/share/keyrings/elastic-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-8.x.list
        sudo apt-get update && sudo apt-get install logstash

    - name: lanzarlogstash
      run: sudo /usr/share/logstash/bin/logstash -t -f logstash.conf
